### ISSUE TITLE
[FEATURE REQUEST] Option to minimise to tray bar on Windows

### ISSUE THREAD

**Issue by cocowalla** [saisandeepvaddi/ten-hands#101]
**Is your feature request related to a problem? Please describe.**
When working I tend to have a lot of Windows open, and it's useful to be able to minimise some things to the Windows tray bar. I can do this with Cmder, for example, so it's always there when I need it, without me having to restart it.

**Describe the solution you'd like**
I'd like to optionally be able to minimise the Ten Hands window to the Windows tray bar.

**Comment by saisandeepvaddi** [comment]
Can you please download v2.0.2. 
Close now hides to tray. Minimize minizes to taskbar.

**Comment by cocowalla** [comment]
Works a treat!
