### ISSUE TITLE
[FEATURE REQUEST] Global hotkey on Windows

### ISSUE THREAD

**Issue by cocowalla** [saisandeepvaddi/ten-hands#102]
**Is your feature request related to a problem? Please describe.**
Kind of following on from #101, it's useful to be able to quickly toggle minimised/maximised state of windows using a global hot key. For example, I can do this with Cmder, such that I can quickly hide/restore it to/from the Windows tray bar at the touch of a button

**Describe the solution you'd like**
I'd like to be able to configure a global hotkey that can be used to minimise Ten Hands to the Windows tray bar, or restore it from the tray bar.

**Comment by saisandeepvaddi** [comment]
Good one. I'll add support for hot key in config.json file. Basically it'll have a default global hot key(s). Users can change them if they want.

**Comment by saisandeepvaddi** [comment]
Added support for this. But, electron doesn't support launching apps when the app is not running anywhere. So for this shortcut to work, Ten Hands has to be running at least in tray.

Download new `Ten Hands` from releases. Check `https://github.com/saisandeepvaddi/ten-hands/wiki/Configuration` for `globalHotKey` property for information on how to configure.

**Comment by cocowalla** [comment]
Perfect, I'll give it a try later today! (I didn't expect it to work when Ten Hands wasn't running; my expectation was to use this to reveal/banish from/to the traybar!)

**Comment by cocowalla** [comment]
This works just as expected, thanks!
