### ISSUE TITLE
[FEATURE REQUEST] Being able to sort tasks in different manners

### ISSUE THREAD

**Issue by asitemade4u** [saisandeepvaddi/ten-hands#110]
Of course, I know one can change the order of the tasks by modifying the underlying JSON project file.
But it would be nice to be able to sort tasks according to different criteria:

- last execution
- name

**Comment by saisandeepvaddi** [comment]
Not released yet, but can you try downloading an alpha version from 
[https://dev.azure.com/saisandeepvaddi/Ten%20Hands/_build/results?buildId=181&view=artifacts&type=publishedArtifacts](https://dev.azure.com/saisandeepvaddi/Ten%20Hands/_build/results?buildId=181&view=artifacts&type=publishedArtifacts)

**Comment by saisandeepvaddi** [comment]
I've released this feature in v2.6.0. Please download and create new issue in case of any comments.
