### ISSUE TITLE
UI issue when window is not fully maximized

### ISSUE THREAD

**Issue by rakip24** [saisandeepvaddi/ten-hands#156]
**OS**: Windows/Linux/macOS with build
Windows

**Where**: Desktop App / Web
Desktop

**Describe the bug**
When the desktop app is not fully maximized, some of the UI elements are not visible.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/34223251/77565415-9611f680-6e9a-11ea-8e79-c1ee83e26d51.png)

**Additional context**

**Comment by saisandeepvaddi** [comment]
Oh oh! What version are you using? Is it happening in this release or did this issue exist in previous releases as well? 

Also, can you please try dragging the project list sidebar on the left side a little to the left and see window re-adjusts itself.

**Comment by rakip24** [comment]
I am using the latest. But, the issue existed in the previous version as well.

Ya, I tried dragging it, didn't really help.

**Comment by rakip24** [comment]
Hey Sai,

Its much better now, initial issue is no longer there, although noticed a
minor issue when you minimize the window further, but its probably not a
normal use case for an average user.

Thanks again!!

[image: image.png]

**Comment by saisandeepvaddi** [comment]
Can you please let me know what is the minor issue you are seeing while minimizing?

**Comment by rakip24** [comment]
Also not sure if this part is useful for the avg user.. UI would look much
cleaner without it IMO..

[image: image.png]

**Comment by saisandeepvaddi** [comment]
I did not get the image.

**Comment by rakip24** [comment]
![image](https://user-images.githubusercontent.com/34223251/78403055-b728c480-75c9-11ea-9451-a95191dac60b.png)

**Comment by rakip24** [comment]
![image](https://user-images.githubusercontent.com/34223251/78403089-c90a6780-75c9-11ea-8499-5bc96000c896.png)

**Comment by saisandeepvaddi** [comment]
oh yeah. I noticed first one.

for long task names, I'll add ellipses. 

May be over the weekend, I'll work & release with all these fixes.

**Comment by rakip24** [comment]
Great. Thanks

**Comment by saisandeepvaddi** [comment]
Released official version with these changes. Please download v2.5.1 that from 
https://github.com/saisandeepvaddi/ten-hands/releases

Closing this issue.
