### ISSUE TITLE
[FEATURE REQUEST] Allow the use of alternative shells

### ISSUE THREAD

**Issue by FinlayDaG33k** [saisandeepvaddi/ten-hands#164]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I run Ten Hands on Windows 10, but by default, Ten Hands uses CMD on Windows.  
This causes my scripts to not run because they rely on Bash.  
Would it be possible to have support for additional shells besides CMD?  

**Additional context**
I personally run Bash by means of Git Bash, but I see other users that would like to use Powershell.  
So I think these should be the shells that are supported by default (on Windows) and allow for the addition of custom shells by the user if they use something else.

**Comment by saisandeepvaddi** [comment]
That's a good feature request @FinlayDaG33k. Ten Hands uses node child_process exec function. I think it can run in different shells if the full path of shell provided. Will work on it.

**Comment by saisandeepvaddi** [comment]
I've released it in v2.6.0. Can you please download v2.6.0. 
Let me know of any issues with shells in a new issue. I'm closing this one.
