### ISSUE TITLE
[Feature Request] Any chance of adding notifications to this app please?

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#172]
Hi Sai Sandeep,

Thanks for this excellent app which is a time saver. :)

I was wondering if you could add notifications to the tasks please. If a task runs for few minutes, it would a great feature to receive notification so that we do not have to keep monitoring the task.

Hope I made sense.

**Comment by saisandeepvaddi** [comment]
Any feature request/bug report/suggestions are welcome.

Can you please elaborate on what kind of notifications you want preferably with an example.

**Comment by reddyshyam** [comment]
I want Windows 10 notifications similar to the one in configuration file shown below.

  "showAppRunningTrayNotification": false,

I would like a notification as soon as a task completes. For example "Project x, Task y has completed." If possible may be add the time taken to the notifcation. 

Please let me know if you need more information.
