### ISSUE TITLE
Though no tasks running, when quitting I get a task running alert/warning

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#173]
**OS**: Windows 10 Pro 20H1 19041.264 Insider 64bit build

**Where**: Desktop App

**Describe the bug**
Though no tasks running, when quitting I get a task running alert/warning

**To Reproduce**
Try to quit when no rask running

**Expected behavior**
Quitting without any alerts/warnings

**Screenshots**
![Screenshot_17May2020_150847](https://user-images.githubusercontent.com/12392746/82141033-d1a0bf80-9850-11ea-98fb-0c72d9b28b0f.png)

**Additional context**

**Comment by saisandeepvaddi** [comment]
Did you update from old version?

Can you please open database file (available from `menu -> edit -> database` or `C:\Users\[username]\.ten-hands\db.json`) and set `runningTaskCount` to `0` and try to reproduce?

**Comment by reddyshyam** [comment]
Hi Sai Sandeep,

Thanks for getting back. Setting it to 0 in database fixed the issue. 

I was tweaking db.json (copying project to a new one and things like that) while app was still running. It might have got the app confused.

Now it is all good. Thanks again for this great app. 👍

**Comment by reddyshyam** [comment]
Hi Sai Sandeep,

This is still happening. My tasks include grails commands, ssh, scp etc... For some reason the app is not keeping a count properly though the UI is correctly showing 0 tasks as screenshot above. 

To avoid such issues, can we not correct the database value accordingly when the UI correctly calculates to 0 please?

**Comment by saisandeepvaddi** [comment]
yeah, will fix soon. Thanks for the the details.

**Comment by saisandeepvaddi** [comment]
Can you please try downloading v2.6.1 and test with it?

**Comment by reddyshyam** [comment]
Hi Sai Sandeep,

Thanks for the quick fix. I just tested and it is working as expected. No more alerts. 👍 

I will continue testing on this tomorrow and let you know if in any other case, it happens again.

Closing the ticket now. Thanks again. Much appreciated! 😃
