### ISSUE TITLE
Using custom shell opens new window

### ISSUE THREAD

**Issue by FinlayDaG33k** [saisandeepvaddi/ten-hands#174]
**OS**: Windows 10 Pro Build 18362

**Where**: Desktop App

**Describe the bug**
When I run my task using a custom shell (`git-bash.exe` in my case), Ten Hands opens a new window for this shell rather than display it in the Ten Hands UI

**To Reproduce**
1. Install Git Bash
2. Point task to use `git-bash.exe`
3. Run task

**Expected behavior**
The console output being shown in Ten Hands rather than a new window

**Screenshots**
Location of the window in the screenshot is just for demonstrational purposes
![](https://i.imgur.com/EEVTtBi.png)

**Comment by saisandeepvaddi** [comment]
I assume you are using `C:\Program Files\Git\git-bash.exe` instead of `C:\Program Files\Git\bin\bash.exe`.

I think `git-bash.exe` is a different process with a window which uses `bin\bash.exe` as a shell. `bin\bash.exe` is the actual shell path.

Let me know if it works.

**Comment by FinlayDaG33k** [comment]
Yes, apparently that was it :) 
Thanks
