### ISSUE TITLE
[FEATURE REQUEST]Can tasks have user input before they run?

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#183]
**Is your feature request related to a problem? Please describe.**
Sorry to bombard you with so many requests. Please feel free to ignore them if you are busy. :)

At the moment task just runs but if the command has input parameters, then task needs to be edited each time, saved and run 

**Describe the solution you'd like**
If there is a way, we can set dynamic params when creating tasks, it would be a good addon, 

For example xyz.bat takes 2 input params 3 and 4.

The task saved would look like **xyz.bat 3 4** 

Now if I want to change the params, I have to edit the task, make changes, save and run it again. 

Now the solution expected is, if we can make params dynamic i.e. **xyz.bat &1 &2** and save the task. When the task is run, app pop's up input boxes for params and when entered, task continues to run with the entered params.

Hope I was clear.

**Additional context**

**Comment by ArthurSantos-L** [comment]
I'm having the same question. Love this project but couldn't find a way to pass parameters to my tasks.
