### ISSUE TITLE
[FEATURE REQUEST] Can you please add so that one can copy text from the output terminals

### ISSUE THREAD

**Issue by stiltet** [saisandeepvaddi/ten-hands#184]
**Is your feature request related to a problem? Please describe.**
At the moment there is no way of copying output text from the built-in terminals.

**Describe the solution you'd like**
It would be really helpful if I can select the text within the terminal and either press CTRL+C or right-click and press copy to copy the outputted text to use in another application.

**Comment by saisandeepvaddi** [comment]
Its Ctrl + Insert. 

Check the following issue for reasons. https://github.com/xtermjs/xterm.js/issues/2478

**Comment by stiltet** [comment]
Okay. That’s great. Can you also if possible add the right-click option to? Since this isn’t self explanatory. Thanks. 😊

**Comment by saisandeepvaddi** [comment]
Yeah, i'll check the right-click option. It's good idea and also expected. Thanks :)

**Comment by saisandeepvaddi** [comment]
I didn't release yet, but you'll be able to download a version with copy with right-click or ctrl+shift+v at following link.

`https://dev.azure.com/saisandeepvaddi/Ten%20Hands/_build/results?buildId=193&view=artifacts&type=publishedArtifacts`

**Comment by saisandeepvaddi** [comment]
The latest versions (v2.10.0 is the latest) have this feature.

Select and right-click or ctrl+shift+c copies the text.
