### ISSUE TITLE
[FEATURE REQUEST]Option to auto start tasks on app load

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#186]
**Is your feature request related to a problem? Please describe.**
I have few tasks I definitely run when I start the app but at the moment I have to manually start them.

**Describe the solution you'd like**
Auto starting the tasks when I open the app will be quitey helpful.

**Additional context**

**Comment by saisandeepvaddi** [comment]
This is interesting. But I think it's only good if users can mark which tasks to auto run. Otherwise, if it starts 1000 tasks that are in the database, it'll be chaos.

**Comment by reddyshyam** [comment]
Hi Sai Sandeep, 

Thanks for getting back. Sorry, I wasn't clear. I meant adding an option to the task to enable if it needs to be autostarted and not a generic feature. 

Hope I was clear
