### ISSUE TITLE
[FEATURE REQUEST]Record timestamp of a task last run

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#187]
**Is your feature request related to a problem? Please describe.**
May be it is just me but I run few tasks plenty of times a day and most of the time forget when was the last time I ran. ;)

**Describe the solution you'd like**
Until the logging is implemented (if at all),, can we have record timestamp of when the task was last run please? This could be an additional entry in the db which should be easy on app.

**Additional context**

**Comment by saisandeepvaddi** [comment]
Yeah, its a good feature to be included. I'll definitely include it in future releases.

In fact, the last run timestamp is avaialble already in db file with property `lastExecutedAt` on tasks. There is no UI yet. This timestamp is currently used in sorting tasks by `Last Executed` option.
