### ISSUE TITLE
Question: What does [ "taskViewStyle": "rows" ] in configuration do?

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#190]
Question: What does "taskViewStyle": "rows" in configuration do and if it is just showing tasks are rows, what are the alternate options?

**Comment by saisandeepvaddi** [comment]
That was meant for a feature I was working on. Currently tasks are displayed in rows one after another. I was working on something that looks like Chrome tabs.

That is not released yet. Where did you see that option any way?

**Comment by reddyshyam** [comment]
Hi Sai Sandeep,

Thanks for getting back. I have seen the option in **config.json**

{
  "port": 5010,
  "enableTerminalTheme": true,
  "globalHotKey": "CommandOrControl+Alt+T",
  "showAppRunningTrayNotification": false,
  "showStatusBar": true,
  "taskViewStyle": "rows",
  "shell": ""
}

**Comment by saisandeepvaddi** [comment]
Oh ok. My mistake for the confusion. You can remove or ignore that. That feature is not available yet. Might take some time.
