### ISSUE TITLE
[FEATURE REQUEST] Can you make app remember its last windows position and size please?

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#200]
**Is your feature request related to a problem? Please describe.**
At the moment it opens in a window and I always maximise it.

**Describe the solution you'd like**
I would like the app to remember last size and position

**Additional context**

**Comment by saisandeepvaddi** [comment]
Ok. I'll add it to next release.

**Comment by reddyshyam** [comment]
Super! Thanks for addressing this as well. 👍 

Much appreciated! 👏
