### ISSUE TITLE
Output window just showing smiley 

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#201]
**OS**: Windows 10 pro 64bit 19041.388

**Where**: Desktop App

**Describe the bug**
Output window just showing smiley. Clearing the output, hiding the output doesnot help remove smiley

**To Reproduce**
Only few tasks show it. 

**Expected behavior**
Display output instead of smiley

**Screenshots**
![Screenshot_16Jul2020_122738](https://user-images.githubusercontent.com/12392746/87637708-419fc900-c760-11ea-9578-40c5e3136b2a.png)

**Additional context**

**Comment by saisandeepvaddi** [comment]
I guess it's because of new webgl terminal renderer.

I should have made it optional.

I'll release a fix tomorrow and make it optional with config file.

**Comment by reddyshyam** [comment]
Thanks Sai Sandeep. 👍

**Comment by saisandeepvaddi** [comment]
Please download v2.8.1 from https://github.com/saisandeepvaddi/ten-hands/releases. This one includes remembering window size when closed.

I do go through each feature requests and ofcourse will work on it as time allows and suits the application. 😄

**Comment by saisandeepvaddi** [comment]
Let me know if it fixes the issue.

**Comment by reddyshyam** [comment]
> Please download v2.8.1 from https://github.com/saisandeepvaddi/ten-hands/releases. This one includes remembering window size when closed.
> 
> I do go through each feature requests and ofcourse will work on it as time allows and suits the application. 😄

Fair enough! 😀

**Comment by reddyshyam** [comment]
> Let me know if it fixes the issue.

Yes, thanks for the quick fix. 🤝 

Closing the ticket.
