### ISSUE TITLE
[FEATURE REQUEST] Config option to decide app close button to close the app or minimise to tray

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#204]
**Is your feature request related to a problem? Please describe.**
At the moment, I close the app by clicking on close button but only to later realise, its not closed but minimised to tray

**Describe the solution you'd like**
An option in config to decide, to minimise to tray or close the app on clicking of close button.

**Additional context**
If close the app is set in config and close button is clicked and if a task is running, an alert saying Task running and asking if still want to close the app, will be a great help.

**Comment by saisandeepvaddi** [comment]
It is already there. I forgot to document it I guess... oops..

Please use `hideToTrayOnClose : false` to make app close completely.

**Comment by reddyshyam** [comment]
Thanks Sai Sandeep. Works perfectly! 👍 🤝 👏
