### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by goldylucks** [saisandeepvaddi/ten-hands#29]
**OS**: Windows/Linux/macOS with build
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

**Describe the bug**
I start the command and it's either not doing anything or outputting an error

**To Reproduce**
start any command

**Expected behavior**
will work and output logs like if running dircetly in terminal

**Screenshots**
![Peek 2019-07-31 13-10](https://user-images.githubusercontent.com/6963212/62203936-d4e7bf00-b394-11e9-9e50-07529fd97de3.gif)

How would I debug this?

**Comment by saisandeepvaddi** [comment]
Thanks for reporting it. Will take a look tonight.

**Comment by saisandeepvaddi** [comment]
Meanwhile, can you try changing `port` to something else in `~/.ten-hands/config.json`

**Comment by goldylucks** [comment]
thanks for checking in, I'm getting same result after setting the port to 3003, which I used previously and I know works.

**Comment by goldylucks** [comment]
Oh now I see ... I got confused with the UI. Got it to work now, thanks!

**Comment by saisandeepvaddi** [comment]
Glad it worked. Can you please tell me what confused you. I'll work on improving it.

**Comment by goldylucks** [comment]
Confused me what to put in `Path` and what in `command`. TBH I'm not sure how I got confused, it seems pretty straightforward. Sorry for that.
